---
- name: playbook test
  hosts: localhost

  tasks:
  - name: create or delete server
    local_action: nova_compute
      state={{ state }}
      login_username={{ os_username }}
      login_password={{ os_password }}
      login_tenant_name={{ os_tenant_name }}
      auth_url={{ auth_url }}
      name={{ name }}
      image_id={{ image }}
      flavor_id={{ flavor }}
      security_groups={{ secgroup }}
      key_name={{ keypair }}

##
## [EOF]
##