#!/usr/bin/env python
#coding: utf-8 -*-

try:
    from novaclient import client as nova_client
    from novaclient import exceptions
    import time
except ImportError:
    print("failed=True msg='novaclient is required for this module'")

DOCUMENTATION = '''
---
module: hp_nova_floating_ip
version_added: "1.6.6"
short_description: Create/Delete floating_ip from OpenStack
description:
   - Create or Remove floating_ip from OpenStack.
options:
   login_username:
     description:
        - login username to authenticate to keystone
     required: true
     default: admin
   login_password:
     description:
        - Password of login user
     required: true
     default: 'yes'
   login_tenant_name:
     description:
        - The tenant name of the login user
     required: true
     default: 'yes'
   auth_url:
     description:
        - The keystone url for authentication
     required: false
     default: 'http://127.0.0.1:35357/v2.0/'
   region_name:
     description:
        - Selecting endpoint for authentication
     required: false
     default: None
   api_version:
     description:
        - The version number or nova api
     required: true
     default: '2'
   floating_ip:
     description:
        - delete floating ip from OpenStack
     required: false
     default: None
   state:
     description:
        - Indicate desired state of the resource
     choices: ['present', 'absent']
     default: present
requirements: ["novaclient"]
'''

EXAMPLES = '''
# Creates new floating_ip for OpenStack
- hp_nova_floating_ip:
       state: present
       login_username: admin
       login_password: admin
       login_tenant_name: admin
'''

def _delete_floating_ip(module, nova):
    try:
        floating_ip = nova.floating_ips.find(ip=module.params['floating_ip'])
        floating_ip.delete()
    except Exception, e:
        module.fail_json( msg = "Error in deleting floating_ip: %s" % e.message)
    module.exit_json(changed = True,
                     id=floating_ip.id,
                     ip=floating_ip.ip,
                     pool=floating_ip.pool)


def _create_floating_ip(module, nova):
    try:
        floating_ip = nova.floating_ips.create()
    except Exception, e:
            module.fail_json( msg = "Error in creating floating_ip: %s " % e.message)
    module.exit_json(changed = True,
                     id=floating_ip.id,
                     ip=floating_ip.ip,
                     pool=floating_ip.pool)


def main():
    module = AnsibleModule(
        argument_spec                   = dict(
        login_username                  = dict(default='admin'),
        login_password                  = dict(required=True),
        login_tenant_name               = dict(required=True),
        auth_url                        = dict(default='http://127.0.0.1:35357/v2.0/'),
        region_name                     = dict(default=None),
        api_version                     = dict(default='2'),
        floating_ip                     = dict(default=None),
        state                           = dict(default='present', choices=['absent', 'present']),
        ),
    )

    nova = nova_client.Client(module.params['api_version'],
                              module.params['login_username'],
                              module.params['login_password'],
                              module.params['login_tenant_name'],
                              module.params['auth_url'],
                              region_name=module.params['region_name'])
    try:
        nova.authenticate()
    except exceptions.Unauthorized, e:
        module.fail_json(msg = "Invalid OpenStack Nova credentials.: %s" % e.message)
    except exceptions.AuthorizationFailure, e:
        module.fail_json(msg = "Unable to authorize user: %s" % e.message)

    if module.params['state'] == 'present':
        _create_floating_ip(module, nova)
    if module.params['state'] == 'absent':
        _delete_floating_ip(module, nova)

# this is magic, see lib/ansible/module.params['common.py
from ansible.module_utils.basic import *
main()

# [EOF]
